[package]
name = "drm-sys"
description = "Bindings to the Direct Rendering Manager API"
version = "0.0.0"
authors = ["Tyler Slabinski <tslabinski@slabity.net>"]
license = "MIT"
build = "build.rs"

[dependencies]
libc = { version = "^0.2.29", default-features = false }

[features]
default = []
use_bindgen = ["bindgen", "pkg-config"]

[build-dependencies]
bindgen = { version = "^0.57.0", optional = true }
pkg-config = { version = "^0.3.19", optional = true }
